frase = str('Curso em video Python')
frase2 = str('   Aprenda Python  ')
print(frase[3])
print(frase[0:21])
print(frase[0:5:2])
print(frase[0:])
print(frase[:9])
print(frase[0::3])
print(len(frase))
print(frase.count('o'))
print(frase.count('o',0,13))
print(frase.find('deo'))
print('Curso' in frase )
print(frase.replace('Curso', 'Aula'))
print(frase.upper())
print(frase.lower())
print(frase.capitalize())
print(frase.title())
print(frase2.strip())
print(frase.rstrip())
print(frase.lstrip())
print(frase.split())
print('-'.join(frase2))
print(frase.upper().count('O'))
print(frase2.replace(' ',''))
print(len(frase2))
print(len(frase2.strip()))